src/AdventureWorks/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AdventureWorks.Models
{
    public class Customer
    {
        public int CustomerID { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Title { get; set; }

        public List<SalesOrder> Orders { get; set; }
    }
}

src/AdventureWorks/Models/SalesOrder.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AdventureWorks.Models
{

    public class SalesOrder
    {
        public int SalesOrderID { get; set; }

        [Display(Name = "order #")]
        public string SalesOrderNumber { get; set; }

        [Display(Name = "purchase order")]
        public string PurchaseOrderNumber { get; set; }

        [Display(Name = "account #")]
        public string AccountNumber { get; set; }

        // TODO: see how moving these to Customer.cs works with Dapper mapping
        [Display(Name = "for")]
        public int CustomerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

        [Display(Name = "created")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime OrderDate { get; set; }

        [Display(Name = "due")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime DueDate { get; set; }

        [Display(Name = "on")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime ShipDate { get; set; }

        [Display(Name = "to")]
        public int ShipToAddressID { get; set; }

        [Display(Name = "via")]
        public int ShipMethodID { get; set; }

        [Display(Name = "via")]
        public string ShipMethodName { get; set; }

        // TODO: move these to Address.cs
        public string AddressLine1 { get; set; }
        public string City { get; set;  }
        public string StateProvinceCode { get; set; }
        public string PostalCode { get; set; }
        public string CountryRegionCode { get; set; }


        [Display(Name = "subtotal")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public decimal SubTotal { get; set; }

        [Display(Name = "tax")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public decimal TaxAmount { get; set; }

        [Display(Name = "freight")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public decimal Freight { get; set; }

        [Display(Name = "total")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public decimal TotalDue { get; set; }

        [Display(Name = "modified")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime ModifiedDate { get; set; }


    }
}

src/AdventureWorks/Models/SalesOrderDetails.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AdventureWorks.Models
{

    public class SalesOrderDetails
    {
        public int SalesOrderID { get; set; }

        public int SalesOrderDetailID { get; set; }

        public int ProductID { get; set; }

        [Display(Name = "product")]
        public string ProductName { get; set; }

        [Display(Name = "quantity")]
        public int OrderQty { get; set; }

        [Display(Name = "list price")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public decimal ListPrice { get; set; }

        [Display(Name = "unit price")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public decimal UnitPrice { get; set; }

        [Display(Name = "discount")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public decimal UnitPriceDiscount { get; set; }

        [Display(Name = "total")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public decimal LineTotal { get; set; }
    }
}

src/AdventureWorks/Controllers/CustomerController.cs
using System.Data.SqlClient;
using AdventureWorks.Repository;
using System.Web.Mvc;
using AdventureWorks.Utils;

namespace AdventureWorks.Controllers
{
    public class FakeHealthCheckController : Controller
    {
        private readonly DbConnectionOptions DbOptions;

        public FakeHealthCheckController(DbConnectionOptions dbOptions)
        {
            DbOptions = dbOptions;
        }

        public ActionResult IsOK()
        {
            using (SqlConnection con = new SqlConnection(DbOptions.ConnectionString))
            {
                con.Open();
                ErrorsSandbox.CheckHealth(con);
            }

            return this.Json(new {OK = true}, JsonRequestBehavior.AllowGet); 
        }
    }

    public class CustomerController : Controller
    {
        private ICustomerRepository _customerRepo { get; }
        private ISalesOrdersRepository _saleRepo { get; }

        public CustomerController(ICustomerRepository customerRepo, ISalesOrdersRepository saleRepo)
        {
            _customerRepo = customerRepo;
            _saleRepo = saleRepo;
        }

        public ActionResult Index()
        {
            return View(this._customerRepo.GetCustomers());
        }

        public ActionResult Details(int id)
        {
            var customer = this._customerRepo.GetCustomer(id);
            customer.Orders = _saleRepo.GetSalesOrders(id);
            return View(customer);
        }
    }
}

src/AdventureWorks/Controllers/HomeController.cs
using System.Web.Mvc;

namespace AdventureWorks.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

src/AdventureWorks/Controllers/SalesOrdersController.cs
using System.Web.Mvc;
using AdventureWorks.Repository;


namespace AdventureWorks.Controllers
{
    public class SalesOrdersController : Controller
    {
        private ISalesOrdersRepository _ordersRepo { get; }

        public SalesOrdersController(ISalesOrdersRepository ordersRepo)
        {
            _ordersRepo = ordersRepo;
        }

        // GET: SalesOrders
        public ActionResult Index()
        {
            return View(this._ordersRepo.GetSalesOrders());
        }

        // GET: SalesOrderDetails
        public ActionResult SalesOrderDetails(int orderId)
        {
            return View( this._ordersRepo.GetSalesOrderDetails(orderId) );
        }


    }
}

src/AdventureWorks/Views/Customer/Details.cshtml
@model AdventureWorks.Models.Customer

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>
        @Html.DisplayFor(model => model.Title) 
        @Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)
    </h4>
    <table class="table">
        <tr>
            <th>order info:</th>
            <th>ship to:</th>
            <th>cost:</th>
        </tr>

        @foreach (var item in Model.Orders)
        {
            <tr class="card-row">
                <td width="240px">
                    <!-- sales order info -->
                    <span class="label">
                        @Html.DisplayNameFor(model => item.CustomerID):
                    </span>
                    @Html.DisplayFor(modelItem => item.FirstName)
                    @Html.DisplayFor(modelItem => item.LastName)
                    <br />
                    <span class="label">
                        @Html.DisplayNameFor(model => item.AccountNumber):
                    </span>
                    @Html.DisplayFor(modelItem => item.AccountNumber)
                    <br />
                    <span class="label">
                        @Html.DisplayNameFor(model => item.SalesOrderNumber):
                    </span>
                    <a class="OrderLink" href="~/SalesOrders/SalesOrderDetails?orderId=@item.SalesOrderID">@item.SalesOrderNumber</a>
                </td>
                <td>
                    <!-- shipping info -->
                    @Html.DisplayFor(modelItem => item.ShipToAddressID)
                    @Html.DisplayFor(modelItem => item.AddressLine1)
                    <br />
                    @Html.DisplayFor(modelItem => item.City),
                    @Html.DisplayFor(modelItem => item.StateProvinceCode),
                    @Html.DisplayFor(modelItem => item.PostalCode),
                    @Html.DisplayFor(modelItem => item.CountryRegionCode)
                    <br />
                    <span class="label">
                        @Html.DisplayNameFor(model => item.ShipMethodID):
                    </span>
                    @Html.DisplayFor(modelItem => item.ShipMethodName)
                    <br />
                    <span class="label">
                        @Html.DisplayNameFor(model => item.ShipDate):
                    </span>
                    @Html.DisplayFor(modelItem => item.ShipDate)
                </td>
                <td>
                    <!-- cost -->
                    <span class="label">
                        @Html.DisplayNameFor(model => item.SubTotal):
                    </span>
                    @Html.DisplayFor(modelItem => item.SubTotal)
                    <br />
                    <span class="label">
                        @Html.DisplayNameFor(model => item.TaxAmount):
                    </span>
                    @Html.DisplayFor(modelItem => item.TaxAmount)
                    <br />
                    <span class="label">
                        @Html.DisplayNameFor(model => item.Freight):
                    </span>
                    @Html.DisplayFor(modelItem => item.Freight)
                    <hr />
                    <span class="label">
                        @Html.DisplayNameFor(model => item.TotalDue):
                    </span>
                    @Html.DisplayFor(modelItem => item.TotalDue)
                </td>
            </tr>
        }

    </table>

</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

src/AdventureWorks/Views/Customer/Index.cshtml
@model IEnumerable<AdventureWorks.Models.Customer>

@{
    ViewBag.Title = "Customers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Customers</h2>
<table id="customers" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.CustomerID }, new {Class="CustomerDetailsLink"})
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts {

    <link href="~/Content/DataTables/datatables.min.css" rel="stylesheet"/>
    <script src="~/Content/DataTables/datatables.min.js"></script>
    <script>
        $(function() {
            $("table#customers").dataTable({ "pageLength": 50 });
        });
    </script>
}

src/AdventureWorks/Views/Home/About.cshtml
@{
    ViewBag.Title = "about";
}
<h3>about</h3>

<p>
    <a href="https://github.com/RandomFractals/AdventureWorks">https://github.com/RandomFractals/AdventureWorks</a>
</p>

<h3>contact</h3>

<address>
    <a href="https://twitter.com/TarasNovak">https://twitter.com/TarasNovak</a>
</address>

src/AdventureWorks/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Adventureworks ASP.NET Web Application</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Sales Orders</h2>
        <p>
            You can see all Sales Orders in the database and find the details.
        </p>
        <p><a class="btn btn-default" href="~/SalesOrders/Index">Sales</a></p>
    </div>
    <div class="col-md-4">
        <h2>Customers</h2>
        <p>Find the list of customers in the AdventureWorks Database and get the details about the customer and his orders.</p>
        <p><a class="btn btn-default" href="~/Customer/Index">Customers</a></p>
    </div>
    <div class="col-md-4">
        <h2>Dapper</h2>
        <p>This appliaction is implemented using Dapper ORM framework.</p>
        <p><a class="btn btn-default" href="https://github.com/StackExchange/Dapper">Learn more &raquo;</a></p>
    </div>
</div>

src/AdventureWorks/Views/SalesOrders/Index.cshtml
@model IEnumerable<AdventureWorks.Models.SalesOrder>

@{
    ViewBag.Title = "orders";
}

<h3>Orders</h3>
<table class="table">
    <tr>
        <th>order info:</th>
        <th>ship to:</th>        
        <th>cost:</th>
    </tr>

@foreach (var item in Model) {
    <tr class="card-row">
        <td width="240px">
            <!-- sales order info -->
            <span class="label">
                @Html.DisplayNameFor(model => model.CustomerID):
            </span>
            @Html.DisplayFor(modelItem => item.FirstName)
            @Html.DisplayFor(modelItem => item.LastName)
            <br />
            <span class="label">
                @Html.DisplayNameFor(model => model.AccountNumber):
            </span>
            @Html.DisplayFor(modelItem => item.AccountNumber)
            <br />
            <span class="label">
                @Html.DisplayNameFor(model => model.SalesOrderNumber):
            </span>
            <a class="OrderLink" href="~/SalesOrders/SalesOrderDetails?orderId=@item.SalesOrderID">@item.SalesOrderNumber</a>
        </td>
        <td>
            <!-- shipping info -->
            @Html.DisplayFor(modelItem => item.ShipToAddressID)
            @Html.DisplayFor(modelItem => item.AddressLine1)
            <br />
            @Html.DisplayFor(modelItem => item.City),
            @Html.DisplayFor(modelItem => item.StateProvinceCode),
            @Html.DisplayFor(modelItem => item.PostalCode),
            @Html.DisplayFor(modelItem => item.CountryRegionCode)
            <br />
            <span class="label">
                @Html.DisplayNameFor(model => model.ShipMethodID):
            </span>
            @Html.DisplayFor(modelItem => item.ShipMethodName)
            <br />
            <span class="label">
                @Html.DisplayNameFor(model => model.ShipDate):
            </span>
            @Html.DisplayFor(modelItem => item.ShipDate)
        </td>
        <td>
            <!-- cost -->
            <span class="label">
                @Html.DisplayNameFor(model => model.SubTotal):
            </span>
            @Html.DisplayFor(modelItem => item.SubTotal)
            <br />
            <span class="label">
                @Html.DisplayNameFor(model => model.TaxAmount):
            </span>
            @Html.DisplayFor(modelItem => item.TaxAmount)
            <br />
            <span class="label">
                @Html.DisplayNameFor(model => model.Freight):
            </span>
            @Html.DisplayFor(modelItem => item.Freight)
            <hr />
            <span class="label">
                @Html.DisplayNameFor(model => model.TotalDue):
            </span>
            @Html.DisplayFor(modelItem => item.TotalDue)
        </td>
    </tr>
}

</table>

src/AdventureWorks/Views/SalesOrders/SalesOrderDetails.cshtml
@model IEnumerable<AdventureWorks.Models.SalesOrderDetails>
@{
    ViewBag.Title = "order details";
}
<br />
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">order details: # @Request.QueryString[0]</h3>
    </div>
    <div class="panel-body">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ProductName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OrderQty)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UnitPrice)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UnitPriceDiscount)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LineTotal)
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OrderQty)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UnitPrice)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UnitPriceDiscount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LineTotal)
                    </td>
                </tr>
            }

        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("back to orders", "")
    </div>
</div>

src/AdventureWorks/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Sales", "Index", "SalesOrders", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Customers", "Index", "Customer", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("About", "About", "Home")</li>
            </ul>
        </div>
    </div>
</div>
<div class="container body-content">
    @RenderBody()
</div>
<footer>

    @{ 
        // Retrieve the ConnectionString from App.config 
        string connectString = System.Configuration.ConfigurationManager.ConnectionStrings["AdventureWorks"].ToString();
        var builder = new System.Data.SqlClient.SqlConnectionStringBuilder(connectString);
        // Retrieve the DataSource property.    
        string IPAddress = builder.DataSource;
        string Database = builder.InitialCatalog;
    }
    <span>Server:</span>
    <a href="https://msftdbprodsamples.codeplex.com/releases/view/125550" target="_blank"
       title="SQL Server Adventure Works 2014">@(IPAddress)</a> |

    <span>Database:</span>
    <a href="https://msftdbprodsamples.codeplex.com/releases/view/125550" target="_blank"
       title="SQL Server Adventure Works">@(Database)</a> |
    |
    <span>Source:</span>
    <a href="https://github.com/RandomFractals/AdventureWorks" target="_blank"
       title="RFI/Adventure Works project github">RFI/Adventure Works</a>
    <span>v. 0.0.1 | &copy;Random Fractals Inc. 2016</span>
</footer>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
<Script language="javascript">
    var url = Math.random() > 0.5 ? "/WebPages/FakeHealthCheck.aspx" : "/FakeHealthCheck/IsOK";
    if (Math.random() < 0.1) url = "/no-way/no-such-page";
    url = url + "?" + (+ new Date());
    var isOk = fetch(url).then().catch();
</Script>
</html>